### ISSUE TITLE
HLS (.m3u8) working fine in 3.2.2, but not in 3.3

### ISSUE THREAD

**Issue by jorbig** [DDVTECH/mistserver#184]
Just a heads up that the new 'stable' 3.2 release broke my HLS stream. The index.m3u8 somehow loads too slow to be played... Reverting to 3.2.2 'fixed' it for me. I don't have time to troubleshoot, but maybe this already helps.

**Comment by Rokamun** [comment]
Hey there,

Thanks for the report, I'll run some checks on it when I can.

What kind of input was the stream? I assume you meant the HLS output being
slow.

With kind regards,

Balder Viëtor
Head of Testing

MistServer

**Comment by jorbig** [comment]
Yes, the output file: `hls/livestream/index.m3u8` downloads eventually, but after something like 10 seconds. Which makes it unplayable. The input is an AAC audio only stream of 32 kbps,

**Comment by jorbig** [comment]
Same issue after updating to 3.4. Rolled back to 3.2.2 once again.

**Comment by irg1008** [comment]
For me I am not being able to stream WHIP from OBS, it gets hung up on "receiving data"

**Comment by Rokamun** [comment]
I'll double-check the audio only streams. We did change quite a bit to the HLS code in this version. So chances are we fixed and then broke it. Sorry about that!

For WHIP I would recommend setting the WebRTC protocol to bind to `0.0.0.0` to force it to IPv4. Chances are it's trying to bind an IPv6 port and I'm actually not sure if we accept WHIP over IPv6 in the current builds. A tutorial on that subject is described [here](https://docs.mistserver.org/howto/input/webrtc_whip) as well.

**Comment by jorbig** [comment]
Still the same problem in 3.5.1... while streaming audio-only (AAC, 32kbps mono), `hls/livestream/index.m3u8` keeps loading in an infinite loop, thus the stream can't be played. Could you please look at this, why does it work fine in 3.2.2 but not in later versions?

**Comment by Rokamun** [comment]
I see what the problem is, we've added logic to base the segmenting/timing of the audio track on the video track. 
If there's no video track it will now create no audio playlist. 

Which is funny considering if you send both audio/video and then request an audio only playlist by selecting that track specifically by not using the master playlist, but just the audio track number it will actually just work.
(`http://mistserveraddress:port/hls/streamname/index.m3u8` vs `http://mistserveraddress:port/hls/streamname/audiotracknum/index.m3u8` ).

**Comment by jorbig** [comment]
Thanks, I can confirm this issue is finally fixed in 3.6!
