### ISSUE TITLE
Could not get RTMP working on Windows

### ISSUE THREAD

**Issue by Taiwan22** [DDVTECH/mistserver#244]
Hello, I'm trying to get Mistserver 3.8 working on Windows 11. I have downloaded the official release and, after installing it, I can log in and configure everything just fine. However, when I try to start RTMP ingest, it never connects. I have the port enabled in the firewall.

Btw, I regularly use Mistserver on my main Linux server, so I’m pretty familiar with it.

I have tried streaming RTMP from both FFmpeg and OBS,pointing to "rtmp://127.0.0.1:1935/live/test", with the same result.

Here is a detailed log from Mist. It seems to accept the connection but never receives any data.

[Mistlog.txt](https://github.com/user-attachments/files/22051806/Mistlog.txt)

**Comment by Thulinma** [comment]
Interesting - that log shows the connection succeeding just fine, but for some reason the RTMP handling process (`MistOutRTMP`) is not able to communicate with the media buffer process (`MistInBuffer`). After 30 seconds, the buffer shuts down because of inactivity, and shortly after the RTMP connection terminates because it cannot reach the buffer... 🤔
I must say I have no idea why this would be at first glance - could you take a look in the `dev/shm` directory inside the directory where you installed Mist, during one of these attempts? There should be some files in there (a cygwin-emulated version of shared memory), and I'm curious if perhaps they are stuck with wrong access permissions or something like that.

**Comment by Taiwan22** [comment]
Thank you for your response. Some files are definitely created.

Here is a screenshot from the shm folder during a connection attempt:

<img width="616" height="567" alt="Image" src="https://github.com/user-attachments/assets/727972b4-dbb6-4d3d-a404-38c23c47c88c" />

**Comment by Taiwan22** [comment]
I have also tried it on multiple Win11 and Win10 machines, with the same result. 
I also compiled it from source using Cygwin, with and without SHM, with the same result. Running it directly from the Cygwin console.
I even tried an old v3.4 build, with the same result.

So maybe there is something fundamentally broken in the Windows builds. Maybe some update broke it.

**Comment by MahmoudAshraf-CIS** [comment]
Am having the same result here on windows 11
- downloaded the 3.8 build from https://mistserver.org/download
- install and follow the CMD instruction to create account 
- in the browser http://localhost:4242/ 
- then create new stream with the source push://*
- In OBS stream setting server : srt://localhost:8889?streamid=live

but the result is OBS seams to be streaming for a few seconds then keeps connecting-disconnecting 
and the preview keeps showing that the stream is offline

**Comment by Taiwan22** [comment]
@Rokamun That's a good question. I've always used a Microsoft account. I tried installing another instance of Windows 11 on a virtual machine, and the problem seems to be related to the Microsoft account. Even on the same VM, if I run it under a Microsoft account it doesn't work, but with a local account it works correctly.

**Comment by Taiwan22** [comment]
As a temporary workaround, I have created another local account (with a password and doesn’t have to be an admin account) and used Shift + right-click and “Run as a different user.”

**Comment by Rokamun** [comment]
That's very good information, thanks for sharing!
Means that we still do "something" wrong with the install permissions. We had set it to SID `S-1-1-0` and figured that the description `A group that includes all users.` would be good enough. Looks like this isn't applicable to Microsoft accounts.

**Comment by Rokamun** [comment]
@Taiwan22 
Any chance you could check out the "[effective permissions](https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-security/access-checks-windows-apis-return-incorrect-results)" for the MistServer installation folder? The access for your Microsoft account would be interesting.

You should be able to access it through:
- Navigate to the MistServer install location
- Right click the "dev" -> Properties
- Go to the security tab -> Advanced (near the bottom)
- Go to the "Effective Permissions" tab, fill in the email address of your microsoft account and check it.

I'm assuming it doesn't have write access, which is most likely the problem.

**Comment by Taiwan22** [comment]
I don't think thats the problem, here is the screenshot:

<img width="714" height="850" alt="Image" src="https://github.com/user-attachments/assets/6103718e-f08b-4fb0-bd8b-a49c596d070c" />

**Comment by Rokamun** [comment]
Hmm, too bad, I would've hoped that setting the installer at the same permission as the cygwin files would help, but I'm guessing it is the wrong way around. We did find that apparently this is a more common issue with Cygwin and a fix would be adding an fstab file to the install location... 
We're not telling it to set the permissions specific by the way. The intent is to have them under normal read/write access for everyone anyways. They're temporarely files that should be getting created/deleted as you use MistServer.

[etc.zip.zip](https://github.com/user-attachments/files/22233173/etc.zip.zip)

Would you be willing to try the following?
In the MistServer installation folder, create a folder "etc" and within that create a file "fstab" which contains the following:
`none /cygdrive cygdrive binary,noacl,posix=0,user 0 0`

The zipfile should contain both already. 
Found the following information that might explain the permission problem.
" By default, Cygwin uses the filesystem's access control lists (ACLs) to implement real POSIX permissions. Some Windows-native program or process may create or modify the ACLs such that Cygwin computes the POSIX permissions as 000. With the noacl mount option, Cygwin ignores filesystem ACLs and only fakes a subset of permission bits based on the DOS readonly attribute. "

I'm thinking our Windows machine isn't triggering this as we first had it installed with a local account which we then later on upgraded to a Microsoft account. I'll have to see if this changes if I do a clean reinstall with a Microsoft account from the start... I'll probably have time for a proper test on this tomorrow.

**Comment by Rokamun** [comment]
Good news, this should now be solved with commit f81d07f94b2988f394f249860384a8b06bffb3e4
Though the ACLs can still be somewhat seen as messed up (side effect of using Cygwin, but not the cygwin terminal). The permissions should be correct & files will be created/deleted accordingly.

Should also be live in the latest development builds: https://r.mistserver.org/dl/mistserver_cyg64Vdev.exe

**Comment by Taiwan22** [comment]
@Rokamun Unfortunately, this didn’t solve my problem either. 
Previously, I also tried creating an "fstab" with different options, but nothing worked. 
I tried setting various permissions for the "shm" folder, and the issue remains the same. If you’re interested, I can send you my test VirtualBox W11 image so you can verify the problem yourself. I even created new MS account...
